export const allPlatform = [
    {name:"PC"},
    {name:"PlayStation"},
    {name:"Xbox"},
    {name:"Nintendo Switch"},
    {name:"iOS"},
    {name:"Android"},
    {name:"Nintendo"},
    {name:"PS Vita"},
    {name:"PSP"},
    {name:"Wii"},
    {name:"GameCube"},
    {name:"Game Boy"},
    {name:"SNES"},
    {name:"NES"},
    {name:"Commodore"},
    {name:"Atari"},
    {name:"Genesis"},
    {name:"SEGA"},
    {name:"Dreamcast"},
    {name:"3DO"},
    {name:"Jaguar"},
    {name:"Game Gear"},
    {name:"Neo Geo"},
    {name:"Play Station 5"},
    {name:"Play Station 4"},
    {name:"Play Station 3"},
    {name:"Play Station 2"},
    {name:"Play Station 1"}
]